### ISSUE TITLE
Time and Frequency text is too big or scale/resolution too small

### ISSUE THREAD

**Issue by khaytsus** [solsticedhiver/rtl_heatmap#2]
python3 rtl_heatmap.py -c charolastra --yticks 60m -i data.csv -o new.png --force

Data:  12 hours, 100MHz to 1100MHz, 100k int

The font for both Y and X are unreadable.  If I make yticks 60m, it's readable but then it's only shown by the hour.  I have a feeling something is going on with scaling/resolution or something because of the generated resolution.  The resolution from this heatmap is 4677x695 vs 11431x1559 from the old heatmap.py.

Attaching sample file using 60m yticks

![new](https://user-images.githubusercontent.com/5436277/55690635-18d83380-5962-11e9-92e2-56d7452f2db1.png)

**Comment by solsticedhiver** [comment]
What is your matplotlib version ?

I have already seen this bug, but I am not sure it's the same or something else. This has to do with the heuristic that define major tick labels

If the resolution is not enough for you, you could define one with `--dpi`

**Comment by solsticedhiver** [comment]
OK.
so there are 3 issues here:
- labelsize is too large (fixed in ce72a551a814fbace2eb3c450dae6ab896473ada)
- heuristic  to define major tick on frequency axe is caught off-guard because frequency span is 999MHz just below 1000MHz (fixed in  6f2dd44750d03b6880c4763ecbb644317b4610ee)
- and the last issue is #3
